### ISSUE TITLE
ChromaControl.Cue.exe using 50% or more of CPU

### ISSUE THREAD

**Issue by heavyoak** [ChromaControl/ChromaControl#1]
after installing this version the ChromaControl.Cue.exe started using 50% of my CPU, across all 12 cores.

the ChromaControl.Aura.exe in this release seems to not function at all, but that might be related to me also having Aura Connect installed previously.

CPU: Ryzen 5 1600

**Comment by AndrewBabbitt97** [comment]
What RGB effect are you using in Synapse for the devices? Static color shouldn't use much CPU but animated ones will use more due to how Synapse sends data, I may be able to add a option to reduce the CPU usage but this will also make animations less fluid/choppy.

As for AURA, ASUS has recently moved Aura to Armory Crate so if you can use that I'd recommend. I had issues with Aura until I updated to it and now it's working well for me again.

**Comment by heavyoak** [comment]
I wasn't using any setting, couldn't even get the icue plugin part to work. it didn't show up in synapse 3 or the actual iCue software even after restarting, just used massive amounts of CPU running in background.

I had to uninstall it just to stop it.

also, your old aura connect still works just fine, and im glad as my Mobo (ROG CROSSHAIR VI HERO) doesn't support Armory Crate as far as ive been able to tell.

**Comment by AndrewBabbitt97** [comment]
I'm looking into this more, and working with the software team at Razer to see why things aren't showing up in Synapse.

I'll keep this updated as I find out more and why the iCUE portion is using so much CPU.

**Comment by AndrewBabbitt97** [comment]
Closing due to the new MSIX beta being out. Open a new issue if you have any other problems.
