### ISSUE TITLE
Can't open AsIO3.sys

### ISSUE THREAD

**Issue by tihomirbz** [ChromaControl/ChromaControl#19]
After installing the utility, I get this error message on Windows startup every time:
https://i.imgur.com/CvZDZU1.jpg

Aac3572DramHal_x64.exe error
Can't open AsIO3.sys!!
Failed with error code 5: Access is denied.

The error appears only when Synapse is already open in the system tray. If I close Synapse, the error goes away and then when I start Synapse manually again, the lighting controls all work as expected.

I think possibly adding a delay on Synapse startup with Windows will be a workaround?

ASUS Armory Crate and Synapse are updated to the latest versions.

**Comment by AndrewBabbitt97** [comment]
What RAM are you using? This is an issue with your RAM HAL installed through Armory Crate. The executable is not a part of my code.

We actually already delay AURA and Synapse connections by 30 seconds by the time Chroma Control starts due to issues with not all devices being ready.

What RAM sticks are you using? This has been seen before on issue #15

In the end the issue lies in the device HAL for your memory installed through Armory Crate, so there's not really anything I can do.

**Comment by tihomirbz** [comment]
The memory is 2x 8GB Corsair Vengeance DDR4-3200

**Comment by AndrewBabbitt97** [comment]
Yeah that's gonna be an awkward one.

Regardless its actually the Aura device HAL complaining and not anything in my code base. Is your ram not being controlled with ICue?

**Comment by tihomirbz** [comment]
Actually this kit doesn't have RGB so I don't have iCue installed. This is the kit:
https://www.corsair.com/uk/en/Categories/Products/Memory/VENGEANCE-LPX/p/CMK16GX4M2B3200C16

Either way, I removed Armoury Crate and instead installed the old AURA utility with the Asus AURA Sync plugin and haven't had issues with syncing there.

**Comment by CyberSavvyy** [comment]
SOLUTION FOUND------>AsusCertService  Error 5 asio3.sys

Well, after 12 hours of investigating this error code, and after creating multiple restore points, I've come to the conclusion that this problem is caused by a disabled service. 

This service is usually enabled by default, but some scan/repair software tools like Advanced System Care disables this service through the manual optimization feature/process. 

To fix this error, you must enable AsusCertService in the optimization panel in whatever repair/scan utility tool you use. If you don't have any repair utility, then do the following steps to enable this service: 

1- Type services in the taskbar search box. 
2- Left-click services once it appears. 
3- Locate AsusCertService. 
4- Righ-click it and choose properties from the menu. 
5- Set the Startup type to Automatic and click on start then OK. 

Not sure if you need to restart here or not. In my case, I didn't need to.

**Comment by Ramazik** [comment]
> SOLUTION FOUND------>AsusCertService Error 5 asio3.sys
> 
> Well, after 12 hours of investigating this error code, and after creating multiple restore points, I've come to the conclusion that this problem is caused by a disabled service.
> 
> This service is usually enabled by default, but some scan/repair software tools like Advanced System Care disables this service through the manual optimization feature/process.
> 
> To fix this error, you must enable AsusCertService in the optimization panel in whatever repair/scan utility tool you use. If you don't have any repair utility, then do the following steps to enable this service:
> 
> 1- Type services in the taskbar search box. 2- Left-click services once it appears. 3- Locate AsusCertService. 4- Righ-click it and choose properties from the menu. 5- Set the Startup type to Automatic and click on start then OK.
> 
> Not sure if you need to restart here or not. In my case, I didn't need to.

Its NOT a solution. This is copy\paste text that one typed and others copy and paste everywhere without even delving into the problem. For example, I don’t even have such a service AsusCertService in services and anywhere. In addition, on another machine where everything works, there is a file C:\Windows\System32\drivers\AsIO3.sys

**Comment by muchenz** [comment]
@CyberSavvyy
Thanks - a lot.

@Ramazik
> Its NOT a solution.

In my case IS. A manually stopped AsysCertService moths age.  And now when a want install software I have 'Can't open AsIO3.sys' message. Run AsysCertService  helps.

**Comment by Gamester25** [comment]
It worked for me, thanks so much <3

> > SOLUTION FOUND------>AsusCertService Error 5 asio3.sys
> > Well, after 12 hours of investigating this error code, and after creating multiple restore points, I've come to the conclusion that this problem is caused by a disabled service.
> > This service is usually enabled by default, but some scan/repair software tools like Advanced System Care disables this service through the manual optimization feature/process.
> > To fix this error, you must enable AsusCertService in the optimization panel in whatever repair/scan utility tool you use. If you don't have any repair utility, then do the following steps to enable this service:
> > 1- Type services in the taskbar search box. 2- Left-click services once it appears. 3- Locate AsusCertService. 4- Righ-click it and choose properties from the menu. 5- Set the Startup type to Automatic and click on start then OK.
> > Not sure if you need to restart here or not. In my case, I didn't need to.
> 
> Its NOT a solution. This is copy\paste text that one typed and others copy and paste everywhere without even delving into the problem. For example, I don’t even have such a service AsusCertService in services and anywhere. In addition, on another machine where everything works, there is a file C:\Windows\System32\drivers\AsIO3.sys
