### ISSUE TITLE
Chroma stops working when exiting the Chromacontrol.Asus Command prompt

### ISSUE THREAD

**Issue by myloba24** [ChromaControl/ChromaControl#201]
Hello, so everything was working fine and then all of the sudden I started getting this error when loading "can't load MsIo.dll(SMB)!" I dont know if it is related but in order for Chroma Control to remain working I have to keep the box open, once I close it the my lights go back and ASUS becomes unreachable in Sypnase.

Anything I can do to fix it, I tried to reinstall it, fix it, and nothing = {

**Comment by AndrewBabbitt97** [comment]
Reinstalling Chroma Control wont change that, because the error is actually coming from Armory Create. Try reinstalling armory create, if that fails report it on the ASUS rog support forum: https://rog.asus.com/forum/showthread.php?130801-Armoury-crate-v5-3-4-0-aura-creator-v3-4-3-0-report-here-if-any-issues
