### ISSUE TITLE
Wallpaper Engine stops Chroma Control from working!

### ISSUE THREAD

**Issue by Setzer123** [ChromaControl/ChromaControl#38]
Yes I have installed everything correct and I have removed and reinstalled everything but I am still having the same issue. When my PC starts up everything is working in sync Razer, Wallpaper Engine, and ICUE for the RAM, but once it changes to a new wall paper Chroma Control become unreachable. It will not start working again until I stop wallpaper engine and stop and start Chroma Control again or restart my PC.
[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6136123/ASUS.log)

**Comment by AndrewBabbitt97** [comment]
You cannot use the ICUE integration in Wallpaper Engine at all if you have the Corsair Chroma Control module installed. This is not supported as Chroma Control expects exclusive control over ICUE devices (which wallpaper engine also expects).

Overall the issue is arising from the use of Wallpaper Engine. Seeing as I don't develop that (wallpaper engine) nor do I have any integrations or code relating to it, it causing connection issues is more of an issue with Wallpaper Engine itself rather than Chroma Control. So my recommendation would be to reach out to the wallpaper engine devs. Seeing as its not open source I dont have the ability to contribute to their code.

**Comment by Setzer123** [comment]
I understand everting about wallpaper engine and there being nothing you can do. But I don’t have the Chroma Control Corsair module installed only Asus Chroma Control. I only have ICUE installed and there plugin for Asus so that Aura Sync can change the RAM RGB. So do you think if I uninstall ICUE this may fix the issue?
