### ISSUE TITLE
Document Usage of GSkill Software When Using Chroma Control

### ISSUE THREAD

**Issue by Phantom2200** [ChromaControl/ChromaControl#40]
Also if you could remove the forced split in the middle of the 8 leds  Thank you for your hard work, you're amazing!

**Comment by Lolovcek** [comment]
Had the same problem, already RMA'd it cause the stick didn't work even when I put it in an other PC :(

**Comment by AndrewBabbitt97** [comment]
GSkill works fine, it's what I have always tested with.

As for the split in colors, this is a limitation of the Razer Broadcast API in Synapse. We repeat the colors that Razer gives us to set every led on every device (we only get 5 colors at a time from Synapse rather than however many LEDs you have in your system)

**Comment by Phantom2200** [comment]
My sticks did not die, just didn't light up; after reinstalling AuraConnect they started working correctly again. Also, am I the only one whose GSkill connection with Razer Chroma never worked at all? It's super weird, using only vanilla Chroma Studio they do not light up at all, but as soon as I start AuraConnect there are no more issues.

Talking about the split, I understand that no matter how many LEDs there are on your peripheral, Razer Chroma Connect registers them only as 4/5 addressable LEDs, but would it be possible to address specifically the LEDs on the RAM to each of the 'virtual LEDS' in order that the light scheme will go only in one direction instead of starting from the middle?

**Comment by Lolovcek** [comment]
my RAM didn't die as well, but it wouldn't light up, reinstalling didn't helped and it stopped working on other computers as well

**Comment by Hotpepere** [comment]
for the RGB communication to be taken into account suddenly on that its is by chroma or by G-skill you must stop your PC and completely turn off the power supply of your computer by unplugging it in order to completely reinitialize the RGB part and the residual power supply from your motherboard if it has internal RGB)
now I warn you that using Razer chroma, chroma control and G-skill and armory crate you end up with 3 management software that want to take control of the RGB of the ram, so the 3 at the same time not great

**Comment by Lolovcek** [comment]
I did everything humanly possible I could do and it still didn't light up

**Comment by AndrewBabbitt97** [comment]
In the end I do not recommend using GSkills software at the same time as Chroma Control if using a motherboard supported via Chroma Control or one of the other Chroma Connect supported motherboards (like MSI).

I will be getting some documentation put in place around supported scenarios.

**Comment by AndrewBabbitt97** [comment]
Closing, as this is no longer relevant with OpenRGB.
