### ISSUE TITLE
Keyboard Sync

### ISSUE THREAD

**Issue by Aape23** [ChromaControl/ChromaControl#63]
Works better than expexcted. But I have problems with the sync of my ROG Strix Flare Keybaord with Chroma Connect. It does not sync up with the rest of the RGB´s.

**Comment by AndrewBabbitt97** [comment]
Need logs from %localappdata%\Packages\ChromaControl.Asus_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs

**Comment by AndrewBabbitt97** [comment]
Keyboards are handled on a "If it works cool, If it doesn't you're on your own" basis.

ASUS has been slowly adding support for keyboards to the AURA SDK from what I have seen. Even once it works I wouldnt recommend using more than the color cycle effect since there's limitations around the Chroma Connect module in Synapse in terms of how many colors get sent to the devices.
