### ISSUE TITLE
Asus Rog Claymore Synchro

### ISSUE THREAD

**Issue by ilPr1nce** [ChromaControl/ChromaControl#68]
Hi Andrew,
I really Appreciate your Job but i've some problems with ChromaControl. It was not able to show my asus Rog Claymore keyboard in the Chroma Studio.
I unistalled and reinstalled The Chroma Control, the Razer Synapse and Armoury Crate without any changes. Can you help me?

**Comment by AndrewBabbitt97** [comment]
Keyboards are handled on a "If it works cool, If it doesn't you're on your own" basis.

ASUS has been slowly adding support for keyboards to the AURA SDK from what I have seen. Even once it works I wouldnt recommend using more than the color cycle effect since there's limitations around the Chroma Connect module in Synapse in terms of how many colors get sent to the devices.
